version: '3'
services:
  zerotier-moon:
    image: seedgou/zerotier-moon:latest
    container_name: zerotier-moon
    command: -4 1.2.3.4 -p 9993
    ports:
      - '9993:9993/udp'
    restart: on-failure
    volumes:
      - './zerotier-moon:/var/lib/zerotier-one'
